name: weather_ai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.24.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  sliding_up_panel: ^2.0.0+1
  gauge_indicator: ^0.4.3
  flutter_bounceable: ^1.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
    - assets/icons/
    - assets/png/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/google_fonts/Kanit-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Kanit-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Kanit-Black.ttf
          weight: 900